


OrdererOrgs:
  
  
  
  - Name: Orderer
    Domain: example.com
    EnableNodeOUs: true
    
    
    
    Specs:
      - Hostname: orderer
        SANS:



OrdererOrgs:
  
  
  
  - Name: Orderer
    Domain: example.com
    EnableNodeOUs: true
    
    
    
    Specs:
      - Hostname: orderer
        SANS:



OrdererOrgs:
  
  
  
  - Name: Orderer
    Domain: example.com
    EnableNodeOUs: true
    
    
    
    Specs:
      - Hostname: orderer
        SANS:



OrdererOrgs:
  
  
  
  - Name: Orderer
    Domain: example.com
    EnableNodeOUs: true
    
    
    
    Specs:
      - Hostname: orderer
        SANS:
